### ISSUE TITLE
Review and suggestions for the improvements

### ISSUE THREAD

**Issue by KrishKayc** [KrishKayc/jirasearch#2]
The app currently does this thing

- Reads the config file for the filters and fields to retrieve.
- Constructs the JQL based on the filters
- Calls the JIRA REST API endpoint with the filters and required fields
- Downloads the results to csv.

Made this app to automate internal metrics preparation with my team.

Need suggestions to improvise the app so that it can used by everyone in generic.

**Comment by malaDev** [comment]
@KrishKayc Here is some kind of improvement that can be done here if agreed
- make this tool available as a standalone command-line that can take some arguments/options
- and these arg can override some pieces of the config file
eg. `bin/ferry --jira.url someUrl  --project ProjectName --sprint SprintName --output file.csv`
With that it would be easier to re-use it without tweaking config when people want to grab data from another project or workspace

What's your thoughts?
