### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by KrishKayc** [KrishKayc/jirasearch#3]
Need to start writing tests for the jirafinder package

**Comment by malaDev** [comment]
I would be happy to contribute on this one.

**Comment by malaDev** [comment]
apparently it needs a lot of refactoring especially for all these channels and goroutines through the process, otherwise implementing unit tests would be absurd

**Comment by KrishKayc** [comment]
@malaDev  Thanks for the suggestions, will create a new ticket for refactoring and close this.
